(defun split-by-half (compartment)
  (let ((half (/ (length compartment) 2)))
    (list (subseq compartment 0 half)
          (subseq compartment half))))

(defun group-by-three (input)
  (loop for i in input
        with all = '()
        with three = '()
        for c = 1 then (1+ c)
        do (push i three)
           (when (equal 0 (mod c 3))
             (push three all)
             (setf three '()))
        finally (return all)))

(defun to-list (string)
  (loop for i across string collecting i))

(defun repeating (compartment)
  (destructuring-bind (a b) (split-by-half compartment)
    (intersection (to-list a) (to-list b))))

(defun repeating-sets (set)
  (destructuring-bind (a b c) set
    (intersection (intersection (to-list a) (to-list b))
                (to-list c))))

(defun to-number (char)
  (let ((number (char-int char))
        (lowercase-a (char-int #\a))
        (uppercase-a (char-int #\A)))
    (if (>= number lowercase-a)
        (1+ (- number lowercase-a))
        (+ 27 (- number uppercase-a)))))

(defun count-priorities (input)
  (loop for i in input sum (to-number (first (repeating i)))))

(defun count-badges (input)
  (loop for i in (group-by-three input)
        sum (to-number (first (repeating-sets i)))))

(defun day03-part1 ()
  (assert (equal 8493 (count-priorities (input)))))

(defun day03-part2 ()
  (assert (equal 2552 (count-badges (input)))))

(defun input ()
  '(
    "jNNBMTNzvTqhQLhQLMQL"
    "VCwnVRCGHHJTdsLtrdhrGdsq"
    "wFJZTbRcnJCbpwpFccZCBfBvPzfpgfgzzWvjSzNP"
    "wDWgDfWNTvwvgFfWfddGldJVprrrVdNlrN"
    "nLnmLSnmMVJvSrHqdV"
    "MsmsbLvtzMjFsCPDsfBwwT"
    "WTqSCqWSWqSgVZqJHpHmHrhMMVrRhBnn"
    "PtLGLGddGGMCpprM"
    "jFvLPPlLjvfjjffsclvPqzzJWTbqNSWZsbSTDzCW"
    "lLSSrfmddlNpnmLdfSPddDdbZQTZgZjbZgjcQZHQPjQgZP"
    "MJMnhzBJVJwvGsMRhRhTsHTjZjHFctbtHZcgZj"
    "vzvBWGJMVGwWGGhGqVBnGzVGDfCDmrqNfrrLSdpSfLSpNmNC"
    "qGWLgfbWhqpLgZbJvTRWJTvMWRslMv"
    "FQwPwNPCVFQQdNcFHNcwwsvslRDRTMDMsVTGJGtRTs"
    "wQHnwnQFPNPdjnnPjhphGqBrfpBBBfZf"
    "mpVpmtPhVtPBLLbQTJpBLZ"
    "vzFMlMzvvRZMTbJQJQbf"
    "srqzvRRqdvzFFrDnvqldFVtwCVCHWNqJHNNcHchCPt"
    "CQJJLZCJLqNMMDDgGLVV"
    "RfRFFszTtzbWTFnRtFrRrWvNHghvBVGgMffvmBVDNgGV"
    "znsjWzstnWjbDnDbTZCpwZcjpjZqQCwSPp"
    "jRrzzrPjLnnpQQDsjj"
    "CTVnTlZWHTcqZBcTTTHqWscQsQDQQDsmmQfvfhwDmv"
    "qlWFWWHTZTlqTFWZHtBVFdlTGdNzRnNngbbSrrSNNzPgPGSz"
    "cWjbcjnssMmRPWbGsWcMbfLBFrZBBLLgZwBrlfLQZtCw"
    "vqpvFHNvhvJzdZQZtlgNNwlrrw"
    "JzqVVVVpzhVJqzhSzJhhDVnFjRRMsPnSRcGMRMjWjWmR"
    "NznNGQgSRQffbbsR"
    "jjjCLwdvLcrhqdblFJsFSPfbDP"
    "qrrvwHqjtLmSSggpBtgn"
    "LGPtFtTfTfTfLrrWTSWGPrrsszbsjZHzgdzSwzbHdsglwl"
    "NhHpVpqNNqbdszRRRb"
    "ccBMJVDNCvvhDNpvNDpnNCVCHFPTmfLTGPMQrfLGmMLWWQQL"
    "dRgRhVLRlncZSSrtLp"
    "WJmwvvvjQvWwFBBvFJPHpwvGWTScGsrZtttGTSsrzTsSZt"
    "FFHJjmjjjPMvfHfwpdRqMppghdRCddDg"
    "NDTRFSnNsVVBDVlM"
    "JjLZWqwjHvfrvmHHvjLWWLlhPlnPlChlQhJQnnzPPBCV"
    "mwHvHmpvwpLmjnvpvLvvNGcTTggRbdTGcbNbTTpS"
    "GGhZQMsmGRfMwfpclgdBlbblBBZgJc"
    "tFvFSTSDnDTTLtcFMbWcBgclJrgd"
    "vzDtzMVtnLTTMTSjSDHtppqhsqqfGjmpPhmsRGPG"
    "MfJtWTTMJfzBbVWPZWQbNnDV"
    "FvlgSHSLvmCvZjgcCQQsPQQsjnbVDNVsdn"
    "HLhclRlHRmHvmLmclLZFSFwRRRpJMtwJwfGGrrtrwfpf"
    "scsswLQcGmQmNHCqvrsHqfff"
    "bdnPSMMMClbBBPCdDDnDVMDWWWvfvWFfFJfNqqNVFqFNfr"
    "bDPTlSTPPbSPjnPSbGmQLCcjLjwzRLcmCG"
    "tFFJjMnFhdcMMJlWtdnlFczBSZGNSjGGbBGZLbZZbLGB"
    "QRgqwwvsLssZnGCz"
    "gqfvvnpfHwRmHTFdFcPdJJmJJc"
    "fccTzVVcfSmdThTTFJPFgg"
    "wLsWfppsjBrnnwjCBZnZqJJQGhBdFJddQhFqdQBG"
    "pZrNCWLwLZLjwwWMftmNzttDcVzVvt"
    "rZnVVjVSMcrwsNbc"
    "dLvQLBLFddvBLzpGmddQCqNswzsMjbhgbblbcwshlb"
    "LLCCWjGBFPmCWdmmPWLdWBpLRZDSPRnHSStRfnZnZTnSSTfJ"
    "ddfnQRbpldRlRLgFglqGCLqsGq"
    "BWBVDZWTBTDPvVTZVDBDNMbhcLLHsFqgvHJsLCJCGcHGsJLH"
    "NPZPDMWZMbZrBVMDDWNmBhMVpSSRpzjjfjpwRnSpwzRzdzjr"
    "bvPSBttgGmZwScwShS"
    "NJspjJLdprzHgjrLzLNrnHQCmmcZQWlcQcNQwlwcQCZC"
    "HdRJsJrdHTbqGMDtgDqT"
    "sNVvSdTstDCtdzdzSCwTzCRhRQjfclMflppjGhffjZcN"
    "rgWlrnLLbqbQMfMphpWjjf"
    "BmrnrFPnnBLlqVwDCtCtVPDTzT"
    "mJMqlVlttQlFVmzFQMQMbQMSSDNwwdSddNddwdDswRDVdR"
    "GGZgcfjrvCCZvgCZqvPHSwRBBsBwswcwBNTDTcSR"
    "GZppfGHGrgGprZhLthFJhFqLWWFhtq"
    "WDHHLtRBHgDnVrWFVFBTdzzZLLjZzjjvddLsvv"
    "JlqmMpCMCGMwbwZddTtCtv"
    "cJJqSplpfSGccJGthFVcVHgFBWBgHgDB"
    "tlFwbWtQFLJhlBFlWPbwmsQndTrrqdnggjqdgnTgTT"
    "GCMBDDCvRpDVpRpHrsgdqTjqgdHcsjHd"
    "MDDvCVGzBGfpzBSNMSRRmwbLWlPmzbPmlJlWbFbJ"
    "fzFzFHBfnvpHFbnzbHfBHZggCGgtZCltDGggdCCVtZVD"
    "sLMNSccQLMSrmLcshLvtCGllPtDdGgtJgmlV"
    "cwLMwwNhQhsWSjqTqHnHbjWTvH"
    "NWlqqhNNnGtNvvWQdrVGBBQdVrwRQr"
    "mppCjppMrDTSgDppCDTMQVRwdBbBQVVbQdQsVB"
    "pgzzTFFFrjHqHnqJFWnh"
    "ncQrhQjqjVQhGsGBbhtsstTp"
    "RllWFLRfZrGlBTbg"
    "vFLLmfNRFSNDfSNjcwqJVrVVzQjc"
    "mmGrgwmGDGcVWVjNNW"
    "nDsqfPCHnpntDssfJPDPjWWhjNTTcjjhTTNcqWcc"
    "DfPCJLpbldRrlrdwmw"
    "dJDNbRhNbJdhqCnrWjhsTWvplg"
    "LMHrttLFcMmcMFLmtGplCggpjjnvTpgnTTFT"
    "czZMzrzVZzHZdNdbDDqDVQNR"
    "sbsJgbsmzdgRgWdg"
    "LLLFBzGMLjzzFtVFwwwCPPRCCqQQTnnCMMCMCC"
    "GllfptwjLjlGFVFjGzpFFNbJDmprrNDsDmDvJhmcvp"
    "SccPbfbncpcfsjbRjMBCTTFGMTCQtJtzFFFJ"
    "vvvdgVhlmlwlgZLgmJhWQCWGGbWtWJhzTJ"
    "NbLNDdbLVmqqmfcsrHcrpPqrcH"
    "HcgDBJSHTCzjjnMNJjrW"
    "VppGMwFwllwwbZZrjvnqmzmnzpqjNv"
    "wZlhtPGPLFVFlGZbVtVTQLLBQRRTSHTSMDCgLs"
    "HPMMnhBHlMnMBPBHJHPWfdnBmjvLZvjTvZTZDgTgTmQmZhZZ"
    "SrzrSScrctrwVzCSCmzQjmLTLvGDvTjGbm"
    "CswstFRNpcwVNRrVVSVwpwpHJnnWWBBHfWHlffWfQMnM"
    "mlFMtqjvMdqjmMCCJZsRQBnszlZz"
    "HcNgcPLcHLwtcfZBTsnsHJBJTzCQ"
    "LGGNhbNtNLDfcgcwfbgthfwFrqqVdFMqMMhMmvShFqmvVv"
    "NbvbBGNvhNhnhpbgpGfBvNgmRjCdPCPCCRCQmmpRdTmTPR"
    "qqFSSqWrtSSccjMdQMHFMBjPMj"
    "SBDSBZZZwGGZNJJg"
    "qTdHSLSFRZRHHZVgpzhbJszchsnsLg"
    "tDvflvrGttDCjlQfmCGvtCftczhbzwJczcJgznNmzJNhwgsp"
    "tQlDCDtrfrtlGrjlQBHFHPVHbBbZqTZdVZBF"
    "MTwvsQJMvvHwVMMJMQNNJRPWWjCllrlWGFlSFCpjgFVSWr"
    "zhcmnRZmqmWjCSFrFqCW"
    "ZbmhZcdZznZfndtwDtMMsRQTTQNRQw"
    "ZhhVqQTvZvVhSmQZcClRCLPCgTGGLbgl"
    "dJWHwndMHswswlGbCmclmLHbbP"
    "dnwwNJnjBjwwdddnjndfWvmvSNZQNrVVmZvZFvvQQv"
    "trlrlrZzsjRjdFhlpwdpnpdp"
    "QqLvvLQmLfQTLbLTfHmqHHLqQgFBdCJBBgggCJdhgJwCggBF"
    "DPDvqLqffqfhSVjVPSPtsj"
    "gsnVdcBcjMMntGMh"
    "RQZLRZlZDRJDCzCjblJSDjQZWWTWPCThMTFGNPTNttGwCFMh"
    "pDlQbSlzpQsjVpjHVfgs"
    "zgqtCtJltdGttJgVGPPJCtJvQFsFFbTFssNDNDsHLbTQbssP"
    "rRcwBnnpcmBqpbLHDspTbFsb"
    "mwRqrqrmWrZnfWmBmnRZlgClgJCJlGJzClGMtG"
    "jlzHllmPnpHlHZBWZJJDWMBNVH"
    "bQrhDbcLgsQrtdVCJWfCCBMMVWrJ"
    "QhGdGcLGwwwtcDzznppPpPwlpnSS"
    "qbpqvWFHbFHHsWwPqPpsVWZTlDcLDddddDrmrcVZDrmT"
    "MCgSSJMCztdmcLzlrlDl"
    "QCRMRSnNtRSqqRjsjLPPvp"
    "ZnZrTfsWWvhVSRmzqqnn"
    "pLGBLBgLCpgGpbdLbgMClJTmmhShSRShqSBDQSRRmQVV"
    "dpJPldgMMbglFdrNWWjHZNccTjZP"
    "CCZCQzwwdmMGDWMmhCMJgpnrnwsTrFNLgnpNgg"
    "jfStHtcjqDPbPtvqvgLNpppnHsrsFgnFNp"
    "fcqqPPPtPSfRVBBRPRPbvQzzhQWGZQVQQZDQMMzGQM"
    "VVlDNDgppgtNltlrJPbjSzPPzjsMsjBBMWMM"
    "LmGRmfmwCqQqbsQBMqJj"
    "cHRcCFfmfmGLJLGFcJLFwfdlhDgptthhHpVrNVdhlvhl"
    "vSSdnBVpscwZcBZB"
    "mLHzqtGtNfGHHFNHMhJMthsbcJtctZTw"
    "GHqHHGzNDNFCfqllCFqVDdPSDQnddvcpPQjdjg"
    "CMWcwGTrvzDWzrDccDCGzTTTplZgSjggjSpSljSjBpSmgmWB"
    "nssRttdsnhsdbFhtVFhNpgwNpBBgHHBBBBZSjNSl"
    "PnVPVPLFtvPvTwwrQq"
    "tlQlqlJCCJWgFrprPjpGVpQzvp"
    "SDbwShHbBZZbhcBdDBDSTrsVpPrzzzHVzNllzGlVNv"
    "BTbbScwRhwZLnLtfJFLFJgWl"
    "VDfPVHfDVMMfHSPSMTVfqgFthFcFrtcdhrhDQdDmdcdt"
    "bWGGHCplWnJNpJCCnlnNwdcwQhmmdmtwddBNcc"
    "HpGCnZGllzlzJWjnCbbnCnRvfvsSTVVSgVLqSsLsLzPPLV"
    "fQqcfqfSDzDWffDZ"
    "NcCLCtPCPMtNBwdthpLhPwzsHrszsZssTsWrDrDVTNNH"
    "twMPBtCpLBCtwMPpJcMBSjjnngqSjQQJbQjjmgmn"
    "vQwVQQVqcJvVJvCpQBCLpdgSFCdjjWWnMSgnSjgjbj"
    "hszPRDTVDWWWRnjWWj"
    "TtDDZsszlPllhPzmPVGssTPpQLcpvpBpZpcfpvrvQvBQLv"
    "sRmGqqzzzgCtRrttCP"
    "cffSwNDddTdfGWtgNCrtGMPP"
    "GGcTwHwHvjqLLjLvlJ"
    "JSdjLJMBdMSrfwwLpWgzWmvDhggzWvfmgD"
    "VsRtVllstHHNllsQsHQRzchcnDmvmvnRvvvcnZ"
    "tGVGCTTTtTFVbsTTNTHsTTqBqBLrBCjqBwqJwqBzLqzw"
    "MhjTJjlSDrplQvFQ"
    "RHttqbNGGmbbLmLmdqbgnFQwrZswQrwDpFpppdwfvQ"
    "gCNmDHHRCLHnWWSCjhWPShPz"
    "BvzpbBwBmsDrmGVgZFDm"
    "TnNRdtlRlCdFFGTLffrrGf"
    "jltNtRCPSlPNtcpwpGzjMBpvbhps"
    "hflJphNDmmbpfnfplbcvLsHVLsrsZsVvCb"
    "FgTFWqTBfFPfFqQqTwHsHccVVLQCZZZCVH"
    "BSSRTGWBgFggBWgBGStTGpzNztmjjzhhzDfNnMjnph"
    "mDDFjjFmVlTZJttffD"
    "hhRvNNCvdNMRLzhSzpptwslNTfNQntsJQZZTlN"
    "WCdMzdMzhMdvRvLhCRLPvjgHmggmbmbblgWcGmcbcG"
    "cScMdhsDhDDdvGzZptzGcnGtpB"
    "NPWjJqrjJWwrSFWRJlrlNWJLtZznLBBzZznLqnpqnpnznV"
    "NWNQwNPjCSQTQhTd"
    "fVVCVccppZMZMMCBzJTNJHWZTWZzNF"
    "QrmmPhDqPhsPRhrlbgRDbbPDJNJTnJzmzzfNNTNHNJNWmnvF"
    "DgbPLbPsQsrbsqLbgllsQQptfwSjwtVLfwdcpCjVwwSp"
    "ZlsmlrZZJcQmhBhlNrsrJRRbRCRggRbzGCRHgRCDGB"
    "fMFvdfVTTdjWTTTfvSjVjpjzcCbFHGPHPDbPHRCFGGRHHG"
    "cdvfSWjfjpdVqSwSvMdLrlrmhqZhhrrLLJQhNr"
    "sWVVmDJsNWNjcSNJZcNcZWWsHTGHTChhHGtHsFFbbsfHhH"
    "nqPRwQRgpQRPQQgMQgQLQqBhvTRtfdfvfCbFtTFFFTtvff"
    "qgrPMLLPpVlbDrVrWD"
    "VcGjcCHcVHPrGnjQDQgDgQDFtdglRtlQ"
    "bWWhfzJhvZWJzNpmRTtsDLDgRTsNddFT"
    "MhJMhJbMmSZbJZwSCtjqcGrrnGjC"
    "FCvpgDsZNsCbvvvpVwcDrjcrmVMwVwHJ"
    "fhfWdPhhhhRQQqzdLSRHRHJjBTTmcrTMrMrwmczcwwTz"
    "qndhdQWndftfhWStfLQQfWgFNsgFpHCtgCNbGZZlZCll"
    "mqTCNhTNmGTLwLNfLrSrgZHDvfPDPv"
    "cjsMQppsFnFslnRQQGMDHGZHSgzHPDZDSf"
    "stWFjcFFsJlQcQtwtbVwCmCthmBTGb"
    "fmsffcqhmqPsnTCnCcQpzjSSNpBWBTQpVSSD"
    "vHbgLRvvvzdgjVVjWg"
    "WltLWvWlqcChrhlf"
    "CtwjffWrdznRtzCwLsmGLlLMsMmMGb"
    "cZFFbgPgJZDchMMPVsmlPGmG"
    "SpNFJBJccNgDcTJJTdbStbnntrCdSrjWnb"
    "qWzgNFqzqHNTBzFNCZCGPpPlHmdPblls"
    "rfSJRJnhhnJDjrfvRStCmpdGsdlDpZZZPbPCmW"
    "cffRvfnnVRjFTWVTLQMFWN"
    "VcHhVrVCQQWhffzcRZznnZFf"
    "dDSCGSsSblwDdmLqvnFZzNZplfpfRZfBnl"
    "tCCwGmSqbqtwsVPjVJWtJHHhQV"
    "fvvTcWzGcCJrJGJvvHMbZTmRQTbpMdQQsR"
    "SgFhVgllLgjLgwlwljFqVFSFdjmBHmZdRMdZpbjpmpjBsHdM"
    "LNqFnlDgVqllwLFLnVSgLFZtCzzzzvCGGccCCDCfvJrv"
    "FczpzmSjVVpSQrzzcRpRcrwqMtJqwtvtLHvQwtLtnJMw"
    "TvbGGbNfGCBBLHtJBHDZDMqD"
    "shgdNTGgvNsflspcPjzVdmppczrV"
    "JHLPLTsSllgSSPPSPLTRTdjCZGZDGGgCdqZtZCZdZt"
    "mhFpnpFwqdGbdFDt"
    "prpWcvnmhmpccBBJMJJlPWLHMDSDWW"
    "GcMcjDbDMMjqHBHVlHvv"
    "rLCrwNJCnwrZNLWQQwzQpRqQPlBRVVBRvvtHqf"
    "zhnrnzdrCwLJCwzwCMGcbdFTscTmgcFlgc"
    "cnwlFrdMsggblgsrMbncwrsWzjGBTjznBzWNzPzTzfjTzf"
    "vvVVHSpQvvRQDJGGLWGfTLTBLQMN"
    "hCmJqVvMSpqqChCJHDZrFsdhrtgFhttZZhts"
    "sfDNqLNpqpzCzLsDqzbCVWRhjTNhShTjHmmjjhStBmvT"
    "wZrlwJwFJGlFMTjhBBZTSTRSbv"
    "wrQrgnPwMsnLbfffVc"
    "hDcwwGWhMMssTcdM"
    "NQmLbNSZHQSHSNpbvfdqfRsZMqssjqdd"
    "LNVtLSSHLSgLNrgwJgJGnBwFMBzD"
    "CRDfCbfjcnRCBVfjVMfMjZpPptplPWtppStpSlBqlq"
    "HdTFLGsdLrzNWtvqPTcpgPZl"
    "JLGmmHrwJGwhjmfMcbDjQC"
    "VShGpPbWjcPCcTLcPN"
    "HqfqDfDFFJDvZRJvqZRRqHZdNcwjllwvQQLQlllccwclCMCT"
    "FddsFmJjjrgGmbSSpS"
    "NRFFLtFtqFLGsdnGbQSs"
    "ljMfMBDlJHgBVHgVflfnwdsSQQbddsSsqnqGfs"
    "PlzDzjljzqRzWzZW"
    "dtzZZbctPzwdlzRwlcdfRgtQJmFmhPSmmSsQQFhsmqSFvm"
    "nDjHnNjjjMnfjNTMWhHQWJSqSSQmhqhm"
    "CDpVCfrjLnnfwtBcpdcbcBZt"
    "sssZSZtDfHbbdtBTCRBzRDFJCBLp"
    "jwWgmWlNQNLlcjWhgQlrQQWrCCJJzFCMVMTzpBMMCVCMTwpT"
    "ggLgrqljLlGvHqttftbP"
    "cSGBFsFcSRZSQGsgBNgVMwMhDQDVfqPjMhwwVq"
    "vnCTLlrpPlHzzjbMfqpbww"
    "rJCnlmClvWvLrTmtTlZcZWSSWPGGdNcFGgcR"
    "lfDDvZZSvLtDtCQZltCqVBWVBCbHJjRdNqWq"
    "pGGhhzMRcqMBqMdVBN"
    "mzgwGrrwhThFGPmGPcFGpwStTfltfDftStDsQRsflDQl"
    "LjnSjLZLBcbBdDqzND"
    "rrfhfMRmpsghfrhGhgQrcPNtZcqNCqdCqPzcNZMM"
    "ZTTgvRpmfffpfgRRhWnVSJJLLWnvJHFlFH"
    "lstcGcttdczzsWVCvQVLCHHnQHWL"
    "rjmJrmfmJMqvQTLvqfGG"
    "JbNrjGjGrMDRJghZggcchhDhzc"
    "tftJQwCgSjpdWHjbRJ"
    "DcwvlZBmGvHjdbczcRpb"
    "sqwDlsBvGNSMQTCNfCTC"
    "DwDrtvMHtBCvcpDcjCMFtBCblJfJGJbZlfzrRlJdbRdZld"
    "sPLPmqhSnLQQSWqlbzRRhfJCJfNJhZ"
    "mVCnWCsQqqLTPWmnDVMFVtHFtMBFpjwM"
    "scChGddJztdNswNsdDsthvmpVmRVcZjmvVvRSMZVSZ"
    "lQLCWgWHCWbFPbbbHqLnLPHHVMpVRgSMmZVSBZBjZVSjRBZp"
    "QrTlTHbPnTsJGtsDdGCr"
    "fMjgFqtFWMhtjcNQSDMmNlCCDMQN"
    "sVHdHdJHwPGPGwwbpJGTbGTvClldmvRSnvlDlLLSlvRnQl"
    "pJbHPHJGVbBswpTcfrBtrhmtrFczzq"
    "SDGSDGVPqqqQPGrTQVTQDrSrJfHJgqhgJqzhJJmWfHpWpzmg"
    "twCdCWMLwbtLLjBddgfcJgRHfRRpfcpRHM"
    "FZdbvFFbVvsWsQsW"
    "rzrRgqGrwgjRVqJCHLzCCWhtDbCC"
    "dTZnNpvBvnJdBpBnsJPvsSCbthLtLbbQShQQLHtSST"
    "BlplPmdlFsslfJmmRfwfwMjw"
    "PPHSrmfHTnmHnHBzRhbFgfbFwzQg"
    "LcsVsGtVLtLqpzwBvgzQRgTTTp"
    "TjLJGTTJWJZZWWZS"
    "tHcshJcJRhLsQscVtccJLRHfvlPjZFSvmvSbvfLFfFFbGZ"
    "drwdTNlwwBTpCdCdwGPrrmjjmjmbSjFPrF"
    "wglnzCDpJtQcztMR"
    "bbMjTbBvgjZNSqldTlVt"
    "wwrcFwsrsnnCQzrCsLnRsQZcNlpJVZHdttZVttSZqJZd"
    "GwLnrsmFCCzqzhvPbPmWmvvfjj"
    "dcnwQdcdrJdSwSFBBqfBfwMqfBfzsh"
    "RgmZpWlCClRlTgBZbhHJJsZjfBHZ"
    "DlNVWgWpgDCCNRDJFcrtQGrrVnrcFPtc"
    "sWSHsdSrHWHsbdsddBsbjmfwffmJDJwcfDQgfvwJDj"
    "ZNGPhRqCCRNGNwSDvmmwwgDhgf"
    "lGlTLTGTSVVFqVTqsFHWntbWBsBsnBHb"
    "QRRgRvDwWDVjmSbDnbTDlDnbqS"
    "rHCPPHrcLFJcllqbTlpq"
    "CldFrNFsgVhhhWgN"
    "qSfMgNqfpmSmlQrRFG"
    "cbBczbtbZTcPWzcrTrmRrLGFTQQFmJ"
    "PBZChtzzcWPcZtBvPjtzBBCfHMMNdDgDpMfVfVpHMqNR"
    "LJPPCHtgtLDfFfvTLwfv"
    "pVGWGGjjjplhpGGVjWnldsvrrMFvfDMTWBdFrfFF"
    "cjlhShjchhjGGmNVjplcQgmTPtHPPJmQgQHgtqgZ"))
